In [1]:
import pandas as pd

products = pd.read_parquet("../data/bronze/products.parquet")

products.head()

,id,title,price,description,category,image,rating
0,1,"Fjallraven - Foldsack No. 1 Backpack, Fits 15 ...",109.95,Your perfect pack for everyday use and walks i...,men's clothing,https://fakestoreapi.com/img/81fPKd-2AYL._AC_S...,"{'count': 120, 'rate': 3.9}"
1,2,Mens Casual Premium Slim Fit T-Shirts,22.30,"Slim-fitting style, contrast raglan long sleev...",men's clothing,https://fakestoreapi.com/img/71-3HjGNDUL._AC_S...,"{'count': 259, 'rate': 4.1}"
2,3,Mens Cotton Jacket,55.99,great outerwear jackets for Spring/Autumn/Wint...,men's clothing,https://fakestoreapi.com/img/71li-ujtlUL._AC_U...,"{'count': 500, 'rate': 4.7}"
3,4,Mens Casual Slim Fit,15.99,The color could be slightly different between ...,men's clothing,https://fakestoreapi.com/img/71YXzeOuslL._AC_U...,"{'count': 430, 'rate': 2.1}"
4,5,John Hardy Women's Legends Naga Gold & Silver ...,695.00,"From our Legends Collection, the Naga was insp...",jewelery,https://fakestoreapi.com/img/71pWzhdJNwL._AC_U...,"{'count': 400, 'rate': 4.6}"

In [6]:
users = pd.read_parquet("../data/bronze/users.parquet")
users.head()

,address,id,email,username,password,name,phone,__v
0,"{'city': 'kilcoole', 'geolocation': {'lat': '-...",1,john@gmail.com,johnd,m38rmF$,"{'firstname': 'john', 'lastname': 'doe'}",1-570-236-7033,0
1,"{'city': 'kilcoole', 'geolocation': {'lat': '-...",2,morrison@gmail.com,mor_2314,83r5^_,"{'firstname': 'david', 'lastname': 'morrison'}",1-570-236-7033,0
2,"{'city': 'Cullman', 'geolocation': {'lat': '40...",3,kevin@gmail.com,kevinryan,kev02937@,"{'firstname': 'kevin', 'lastname': 'ryan'}",1-567-094-1345,0
3,"{'city': 'San Antonio', 'geolocation': {'lat':...",4,don@gmail.com,donero,ewedon,"{'firstname': 'don', 'lastname': 'romer'}",1-765-789-6734,0
4,"{'city': 'san Antonio', 'geolocation': {'lat':...",5,derek@gmail.com,derek,jklg*_56,"{'firstname': 'derek', 'lastname': 'powell'}",1-956-001-1945,0

In [7]:
carts = pd.read_parquet("../data/bronze/carts.parquet")
carts.head()

,id,userId,date,products,__v
0,1,1,2020-03-02 00:00:00+00:00,"[{'productId': 1, 'quantity': 4}, {'productId'...",0
1,2,1,2020-01-02 00:00:00+00:00,"[{'productId': 2, 'quantity': 4}, {'productId'...",0
2,3,2,2020-03-01 00:00:00+00:00,"[{'productId': 1, 'quantity': 2}, {'productId'...",0
3,4,3,2020-01-01 00:00:00+00:00,"[{'productId': 1, 'quantity': 4}]",0
4,5,3,2020-03-01 00:00:00+00:00,"[{'productId': 7, 'quantity': 1}, {'productId'...",0