In [1]:
import pandas as pd

Produtos por categoria:

In [7]:
pd.read_parquet(
    "../data/gold/products_by_category.parquet"
)

           category  total_products
0       electronics               6
1          jewelery               4
2    men's clothing               4
3  women's clothing               6

Preço médio:

In [8]:
pd.read_parquet(
    "../data/gold/avg_price_by_category.parquet"
)

           category   avg_price
0       electronics  332.498333
1          jewelery  220.995000
2    men's clothing   51.057500
3  women's clothing   26.286667

Top produtos:

In [9]:
pd.read_parquet(
    "../data/gold/top_products.parquet"
)

,product_id,title,category,total_quantity
0,1,"Fjallraven - Foldsack No. 1 Backpack, Fits 15 ...",men's clothing,20
1,3,Mens Cotton Jacket,men's clothing,6
2,2,Mens Casual Premium Slim Fit T-Shirts,men's clothing,5
3,12,WD 4TB Gaming Drive Works with Playstation 4 P...,electronics,3
4,10,SanDisk SSD PLUS 1TB Internal SSD - SATA III 6...,electronics,2
5,5,John Hardy Women's Legends Naga Gold & Silver ...,jewelery,2
6,8,Pierced Owl Rose Gold Plated Stainless Steel D...,jewelery,1
7,7,White Gold Plated Princess,jewelery,1
8,9,WD 2TB Elements Portable External Hard Drive -...,electronics,1
9,18,MBJ Women's Solid Short Sleeve Boat Neck V,women's clothing,1

Top usuários:

In [10]:
pd.read_parquet(
    "../data/gold/top_users.parquet"
)

   user_id firstname  lastname         city  total_items
0        1      john       doe     kilcoole           27
1        3     kevin      ryan      Cullman            6
2        4       don     romer  San Antonio            5
3        2     david  morrison     kilcoole            3
4        8   william   hopkins         mesa            1